import {Html5Video, Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import type {Scene, Theme} from '../types';

const Header = ({scene, theme}: {scene: Scene; theme: Theme}) => <><div style={{fontSize: 27, color: theme.accent, fontWeight: 850, letterSpacing: 2}}>{scene.eyebrow}</div><h2 style={{fontSize: 78, lineHeight: 1.12, margin: '22px 0 28px'}}>{scene.headline}</h2></>;

const Material = ({scene, theme}: {scene: Scene; theme: Theme}) => {
  const material = scene.materialIds[0];
  const source = material ? (/^(?:blob:|https?:|data:)/.test(material) ? material : staticFile(material)) : '';
  const kind = material ? scene.materialKinds?.[material] || (/\.mp4$/i.test(material) ? 'video' : 'image') : null;
  return <div style={{height: 610, padding: 14, borderRadius: 34, background: theme.surface, boxShadow: `0 24px 70px ${theme.primary}28`}}><div style={{height: 42, display: 'flex', alignItems: 'center', gap: 10, paddingLeft: 12}}>{['#ff6b6b', '#ffd166', '#65e572'].map((color) => <span key={color} style={{width: 13, height: 13, borderRadius: 99, background: color}} />)}</div><div style={{height: 540, borderRadius: 22, overflow: 'hidden', background: '#f6f8fc', color: '#182230'}}>{kind === 'video' ? <Html5Video src={source} loop muted={scene.muteMaterialVideo} style={{width: '100%', height: '100%', objectFit: 'cover'}} /> : kind === 'image' ? <Img src={source} style={{width: '100%', height: '100%', objectFit: 'contain'}} /> : <div style={{height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', padding: 30}}>{scene.items.slice(0, 3).map((item, index) => <div key={item} style={{padding: '22px 24px', margin: '9px 0', borderRadius: 18, background: 'white', fontSize: 30, fontWeight: 800}}><small style={{color: '#68758a', marginRight: 14}}>0{index + 1}</small>{item}</div>)}</div>}</div></div>;
};

export const PortraitScene = ({scene, theme}: {scene: Scene; theme: Theme}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  if (scene.type === 'opening') {
    const scale = spring({frame, fps, config: {damping: 18, stiffness: 110}, durationInFrames: 35});
    return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center'}}><div style={{fontSize: 28, color: theme.accent, fontWeight: 850, letterSpacing: 3}}>{scene.eyebrow}</div><h1 style={{fontSize: 104, lineHeight: 1.06, margin: '34px 0', transform: `scale(${scale})`, transformOrigin: 'left center'}}>{scene.headline}</h1><p style={{fontSize: 39, lineHeight: 1.55, color: theme.muted}}>{scene.body}</p></div>;
  }
  if (scene.type === 'statement') return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center'}}><Header scene={scene} theme={theme} /><p style={{fontSize: 36, lineHeight: 1.55, color: theme.muted, margin: 0}}>{scene.body}</p><div style={{marginTop: 66, padding: '48px 42px', borderRadius: 34, background: theme.surface, border: `2px solid ${theme.primary}`}}><div style={{fontSize: 24, color: theme.muted}}>核心判断</div><div style={{fontSize: 55, lineHeight: 1.28, fontWeight: 900, marginTop: 20, color: theme.accent}}>{scene.emphasis[0]}</div></div></div>;
  if (scene.type === 'flow') return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center'}}><Header scene={scene} theme={theme} /><div style={{display: 'grid', gridTemplateColumns: scene.items.length > 4 ? '1fr 1fr' : '1fr', gap: 18}}>{scene.items.map((item, index) => {const opacity = interpolate(frame, [index * 10, index * 10 + 16], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}); return <div key={item} style={{opacity, display: 'grid', gridTemplateColumns: '72px 1fr', alignItems: 'center', padding: '25px 26px', borderRadius: 24, background: theme.surface, borderLeft: `7px solid ${index === scene.items.length - 1 ? theme.accent : theme.primary}`}}><div style={{fontSize: 23, color: theme.muted}}>0{index + 1}</div><div style={{fontSize: 34, lineHeight: 1.3, fontWeight: 820}}>{item}</div></div>;})}</div></div>;
  if (scene.type === 'comparison') return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center'}}><Header scene={scene} theme={theme} /><div style={{display: 'grid', gridTemplateColumns: '1fr', gap: 26}}>{scene.items.slice(0, 2).map((item, index) => <div key={item} style={{minHeight: 250, padding: 40, borderRadius: 32, background: index === 0 ? theme.surface : `${theme.primary}24`, border: `2px solid ${index === 0 ? theme.muted : theme.primary}`}}><div style={{fontSize: 24, color: index === 0 ? theme.muted : theme.accent}}>{scene.emphasis[index] || `对比 ${index + 1}`}</div><div style={{fontSize: 43, lineHeight: 1.35, fontWeight: 850, marginTop: 20}}>{item}</div></div>)}</div></div>;
  if (scene.type === 'screenshot') return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center'}}><Header scene={scene} theme={theme} /><p style={{fontSize: 34, color: theme.muted, lineHeight: 1.5, margin: '0 0 36px'}}>{scene.body}</p><Material scene={scene} theme={theme} /></div>;
  return <div style={{display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'center', textAlign: 'left'}}><Header scene={scene} theme={theme} /><p style={{fontSize: 38, color: theme.muted, lineHeight: 1.55}}>{scene.body}</p>{(scene.emphasis[0] || scene.items[0]) ? <div style={{marginTop: 52, padding: '28px 36px', borderRadius: 25, background: theme.accent, color: theme.background, fontSize: 36, lineHeight: 1.35, fontWeight: 900}}>{scene.emphasis[0] || scene.items[0]}</div> : null}</div>;
};
